name = "huang-shan-global-fe"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

# Environment variables for build time
[vars]
NEXT_PUBLIC_API_URL="https://huangshan-api.xox-labs-server.workers.dev"
NEXT_PUBLIC_ENVIRONMENT="production"
